vim.api.nvim_create_user_command("PackList", require "utils.pack_list", { nargs = "*", desc = "list installed plugins and their status" })
vim.api.nvim_create_user_command("PackCheck", require "utils.pack_check", { nargs = "*", desc = "check for pending plugin updates (online)" })
vim.api.nvim_create_user_command("PackUpdate", require "utils.pack_update", { nargs = "*", desc = "update all plugins or specific ones" })
vim.api.nvim_create_user_command("PackClean", require "utils.pack_clean", { nargs = "*", desc = "remove inactive plugins from disk" })
vim.api.nvim_create_user_command("PackRemoveAll", require "utils.pack_remove_all", { nargs = "*", desc = "remove plugins from disk (including active)" })
