# source-file ~/.config/tmux/overwrite.conf

# Show the running program in the tab
set -gw automatic-rename-format '#{pane_current_command}'

# New window opens in session dir, not current pane dir
bind c new-window -c "#{session_path}"

# Browser-like tab switching
bind -n S-Left previous-window  # Shift+Left Arrow
bind -n S-Right next-window  # Shift+Right Arrow
bind -n M-j previous-window  # Alt+j
bind -n M-l next-window  # Alt+l

# Move current tab left/right with Shift+Alt+Arrow keys
bind -n S-M-Left swap-window -t -1  # Shift+Alt+Left Arrow
bind -n S-M-Right swap-window -t +1  # Shift+Alt+Right Arrow

# Browser-like tab switching with Ctrl+number
bind -n C-1 select-window -t 1  # Ctrl+1
bind -n C-2 select-window -t 2  # Ctrl+2
bind -n C-3 select-window -t 3  # Ctrl+3
bind -n C-4 select-window -t 4  # Ctrl+4
bind -n C-5 select-window -t 5  # Ctrl+5
bind -n C-6 select-window -t 6  # Ctrl+6
bind -n C-7 select-window -t 7  # Ctrl+7
bind -n C-8 select-window -t 8  # Ctrl+8
bind -n C-9 select-window -t 9  # Ctrl+9

# plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'

run '~/.tmux/plugins/tpm/tpm'
