#!/bin/bash

set -e

select_projects() {
    find ~/projects -mindepth 1 -maxdepth 1 -type d | fzf || true
}

select_other() {
    {
        find ~/scratch -mindepth 1 -maxdepth 1 -type d
        printf '%s\n' "$HOME/dotfiles"
        printf '%s\n' "$HOME/Work"
    } | fzf || true
}

select_learns() {
    find ~/learns -mindepth 1 -maxdepth 2 -type d -not -path "*/.git*" | fzf || true
}

if [[ $1 == "projects" ]]; then
    selected=$(select_projects)
elif [[ $1 == "other" ]]; then
    selected=$(select_other)
elif [[ $1 == "learns" ]]; then
    selected=$(select_learns)
elif [[ $# -eq 1 ]]; then
    selected=$1
else
    echo "invalid argument. Usage: $0 [projects|other|learns]"
    exit 1
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux || true)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s "$selected_name" -c "$selected"
    exit 0
fi

if ! tmux has-session -t="$selected_name" 2>/dev/null; then
    tmux new-session -ds "$selected_name" -c "$selected"
fi

tmux switch-client -t "$selected_name"
