--ozone-platform=wayland
--enable-features=UseOzonePlatform
--ozone-platform-hint=auto
--force-device-scale-factor=1
--load-extension=/usr/share/omarchy/default/chromium/extensions/yt-dlp,/usr/share/omarchy/default/chromium/extensions/whatsapp-slim
--password-store=gnome-libsecret
