return {
    "xiyaowong/transparent.nvim",
    -- enabled = false,
    config = function()
        require("transparent").setup {
            groups = {
                "Normal",
                "NormalNC",
                -- "Comment",
                -- "Constant",
                -- "Special",
                -- "Identifier",
                -- "Statement",
                -- "PreProc",
                -- "Type",
                -- "Underlined",
                -- "Todo",
                -- "String",
                -- "Function",
                -- "Conditional",
                -- "Repeat",
                -- "Operator",
                -- "Structure",
                -- "LineNr",
                -- "NonText",
                -- "SignColumn",
                -- "CursorLine",
                -- "CursorLineNr",
                -- "StatusLine",
                -- "StatusLineNC",
                -- "EndOfBuffer",

                "NeoTreeNormal",
                "NeoTreeNormalNC",
                -- "NeoTreeVertSplit",
                -- "NeoTreeWinSeparator",
                -- "NeoTreeEndOfBuffer",
                -- "NeoTreeRootName",
                -- "NeoTreeDirectoryName",
                -- "NeoTreeDirectoryIcon",
                -- "NeoTreeFileName",
                -- "NeoTreeFileIcon",
                -- "NeoTreeFloatNormal",
                -- "NeoTreeFloatBorder",
                --
                "TelescopeNormal",
                "TelescopeBorder",
                "TelescopePromptNormal",
                "TelescopePromptBorder",
                "TelescopePromptTitle",
                "TelescopePreviewTitle",
                "TelescopeResultsTitle",
                "TelescopePreviewNormal",
                "TelescopePreviewBorder",
                "TelescopeResultsNormal",
                "TelescopeResultsBorder",
                -- "TelescopeSelection",
                "TelescopeMatching",
            },
            extra_groups = {},
            exclude_groups = {},
            on_clear = function() end,
        }

        vim.cmd "TransparentEnable"
    end,
}
