import = [ "tokyo-night.toml" ] 

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["-c", "$HOME/.scripts/tmux/init.sh"]

[window]
startup_mode = "Maximized"
decorations = "None"
dimensions = { columns = 0, lines = 0 }
padding = { x = 5, y = 0 }
opacity = 0.95
# blur = true

[font]
normal = { family = "CaskaydiaMono Nerd Font", style = "Regular" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
size = 12

# Tokyo Night
[colors.bright]
black = "#444b6a"
blue = "#7da6ff"
cyan = "#0db9d7"
green = "#b9f27c"
magenta = "#bb9af7"
red = "#ff7a93"
white = "#acb0d0"
yellow = "#ff9e64"

[colors.normal]
black = "#32344a"
blue = "#7aa2f7"
cyan = "#449dab"
green = "#9ece6a"
magenta = "#ad8ee6"
red = "#f7768e"
white = "#787c99"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
foreground = "#a9b1d6"
