[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["-c", "$HOME/.scripts/tmux/init.sh"]

[window]
padding = { x = 16, y = 14 }
decorations = "None"
opacity = 0.98

[keyboard]
bindings = [
  { key = "F11", action = "ToggleFullscreen" }
]

